export const images = {
  logo: require('./app-logo.png'),
  splashBackground: require('./splash-background.png'),
  onboarding: [
    require('./onboarding-0.png'),
    require('./onboarding-1.png'),
    require('./onboarding-2.png'),
    require('./onboarding-3.png'),
    require('./onboarding-4.png'),
  ],
  locations: {
    neuschwansteinCastle: require('./neuschwanstein-castle.png'),
    eibseeLake: require('./eibsee-lake.png'),
    watzmannView: require('./watzmann-view.png'),
    partnachGorge: require('./partnach-gorge.png'),
    mittenwaldStreets: require('./mittenwald-streets.png'),
    rothenburg: require('./rothenburg-ob-der-tauber.png'),
    nurembergOldTown: require('./nuremberg-old-town.png'),
    regensburgOldTown: require('./regensburg-old-town.png'),
    bambergOldTown: require('./bamberg-old-town.png'),
    burghausenCastle: require('./burghausen-castle.png'),
    bmwWelt: require('./bmw-welt.png'),
    audiForum: require('./audi-forum.png'),
    deutschesMuseum: require('./deutsches-museum.png'),
    augsburgTextileMuseum: require('./augsburg-textile-museum.png'),
    manMuseum: require('./man-museum.png'),
    walchensee: require('./walchensee.png'),
    altmuhlValley: require('./altmuhl-valley.png'),
    tegernseeLakeside: require('./tegernsee-lakeside.png'),
    chiemseeIslands: require('./chiemsee-islands.png'),
    berchtesgadenTrails: require('./berchtesgaden-trails.png'),
  },
  stories: {
    beyondOktoberfest: require('./blog-beyond-oktoberfest.png'),
    calmRoute: require('./blog-calm-route.png'),
    seasons: require('./blog-seasons.png'),
    industrialBavaria: require('./blog-industrial-bavaria.png'),
    quietPlaces: require('./blog-quiet-places.png'),
  },
} as const;
